edc.participant.id=federation-consumer
edc.dsp.callback.address=http://edc-consumer:8284/protocol
web.http.port=8280
web.http.path=/api
web.http.management.port=8281
web.http.management.path=/management
web.http.protocol.port=8284
web.http.protocol.path=/protocol
web.http.public.port=8285
web.http.public.path=/public
web.http.control.port=8282
web.http.control.path=/control
web.http.signaling.port=8286
web.http.signaling.path=/signaling
edc.transfer.proxy.token.signer.privatekey.alias=private-key
edc.transfer.proxy.token.verifier.publickey.alias=public-key
