edc.participant.id=factory-2
edc.dsp.callback.address=http://localhost:21194/protocol
web.http.port=21191
web.http.path=/api
web.http.management.port=21193
web.http.management.path=/management
web.http.protocol.port=21194
web.http.protocol.path=/protocol
web.http.public.port=21291
web.http.public.path=/public
web.http.control.port=21192
web.http.control.path=/control
web.http.signaling.port=21195
web.http.signaling.path=/signaling
edc.dataplane.api.public.baseurl=http://localhost:21291/public
edc.dataplane.proxy.public.endpoint=http://localhost:21291/public
edc.transfer.proxy.token.signer.privatekey.alias=private-key
edc.transfer.proxy.token.verifier.publickey.alias=public-key
